### Get list
GET http://localhost:3001/dogs

### Get list filtered success
GET http://localhost:3001/dogs?name=ame

### Get list filtered error
GET http://localhost:3001/dogs?name=nonexistence

### Get dog by id success
GET http://localhost:3001/dogs/10

### Get dob by id error
GET http://localhost:3001/dogs/invalid

### Create dog
POST http://localhost:3001/dogs
Content-Type: application/json

{
  "name": "Boby",
  "image": "url image",
  "lifeSpan": "life span",
  "heightMin": "height min",
  "heightMax": "height max",
  "weightMin": "weight min",
  "weightMax": "weight max",
  "temperaments": [
    "temperament 1",
    "temperament 2"
  ]
}

### 404 Response
GET http://localhost:3001/not-found

### 500 Response
GET http://localhost:3001/throw